# Problem 1:

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

 Yes, the dateypes of the "list_" and "array_list" are different. 

In [9]:
print(f"Datatype of \"list_\" is = {type(list_)}")
print(f"Datatype of \"array_list\" is = {type(array_list)}")

Datatype of "list_" is = <class 'list'>
Datatype of "array_list" is = <class 'numpy.ndarray'>


# Problem 2:

In [15]:
for i in list_:
    print(f"Datatype of element {i} in \"list_\" is {type(i)}")

Datatype of element 1 in "list_" is <class 'str'>
Datatype of element 2 in "list_" is <class 'str'>
Datatype of element 3 in "list_" is <class 'str'>
Datatype of element 4 in "list_" is <class 'str'>
Datatype of element 5 in "list_" is <class 'str'>


In [16]:
for i in array_list:
    print(f"Datatype of element {i} in \"array_list\" is {type(i)}")

Datatype of element 1 in "array_list" is <class 'numpy.str_'>
Datatype of element 2 in "array_list" is <class 'numpy.str_'>
Datatype of element 3 in "array_list" is <class 'numpy.str_'>
Datatype of element 4 in "array_list" is <class 'numpy.str_'>
Datatype of element 5 in "array_list" is <class 'numpy.str_'>


# Problem 3:

In [17]:
array_list = np.array(object = list_, dtype = int)

Now the datatype of the elements in "array_list" will be different.

In [19]:
for i in list_:
    print(f"Datatype of element {i} in \"list_\" is {type(i)}")

Datatype of element 1 in "list_" is <class 'str'>
Datatype of element 2 in "list_" is <class 'str'>
Datatype of element 3 in "list_" is <class 'str'>
Datatype of element 4 in "list_" is <class 'str'>
Datatype of element 5 in "list_" is <class 'str'>


In [20]:
for i in array_list:
    print(f"Datatype of element {i} in \"array_list\" is {type(i)}")

Datatype of element 1 in "array_list" is <class 'numpy.int32'>
Datatype of element 2 in "array_list" is <class 'numpy.int32'>
Datatype of element 3 in "array_list" is <class 'numpy.int32'>
Datatype of element 4 in "array_list" is <class 'numpy.int32'>
Datatype of element 5 in "array_list" is <class 'numpy.int32'>


# Problem 4:

In [25]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [31]:
print(f"The shape of the given array is {np.shape(num_array)}")
print(f"The size of the given array is {np.size(num_array)}")

The shape of the given array is (2, 3)
The size of the given array is 6


# Problem 5:

In [38]:
matrix = np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [39]:
print(f"The shape of the matrix is is {np.shape(matrix)}")
print(f"The size of the matrix is {np.size(matrix)}")

The shape of the matrix is is (3, 3)
The size of the matrix is 9


# Problem 6:

In [43]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
print(f"The shape of the identity_matrix is is {np.shape(identity_matrix)}")
print(f"The size of the identity_matrix is {np.size(identity_matrix)}")

The shape of the identity_matrix is is (5, 5)
The size of the identity_matrix is 25
